using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace cs361_finalProject
{
    class PuzzleDatabase
    {
        protected static List<string[,]> puzzles = new List<string[,]>
        {
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null,  "4", null, null,  "1", null, null,  "6", null,  "5" },
                            { null, null,  "6", null, null, null,  "2", null, null,  "8" },
                            { null, null, null, null,  "7",  "4", null,  "2", null, null },
                            { null, null, null, null,  "3", null,  "1",  "7", null,  "4" },
                            { null,  "3", null,  "4",  "8", null,  "5",  "9", null,  "1" },
                            { null,  "1", null,  "9",  "4", null,  "7", null, null, null },
                            { null, null, null,  "5", null,  "7",  "4", null, null, null },
                            { null,  "8", null, null,  "5", null, null, null,  "4", null },
                            { null,  "9", null,  "1", null, null,  "3", null, null,  "7" } },
            //easy
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null,  "6", null,  "7",  "2", null, null, null, null,  "3" },
                            { null, null,  "1", null, null, null,  "9", null,  "8",  "2" },
                            { null,  "9", null,  "2", null,  "7", null,  "4", null,  "6" },
                            { null,  "8", null, null, null, null, null,  "6", null, null },
                            { null, null,  "3",  "9", null,  "8", null,  "1",  "2", null },
                            { null, null, null,  "1", null, null, null, null, null,  "4" },
                            { null,  "1", null,  "3", null,  "2", null,  "9", null,  "5" },
                            { null,  "5",  "9", null,  "7", null, null, null,  "4", null },
                            { null,  "2", null, null, null, null,  "6",  "3", null,  "1" } },
            //easy
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null, null, null, null, null, null,  "4", null, null,  "2" },
                            { null,  "3", null, null,  "9", null, null,  "6",  "4",  "8" },
                            { null, null,  "5", null,  "8", null, null,  "9", null,  "1" },
                            { null, null,  "6", null, null, null,  "3",  "7", null, null },
                            { null,  "7",  "4",  "9", null, null, null,  "3",  "2",  "6" },
                            { null, null, null,  "2",  "6", null, null, null,  "8", null },
                            { null,  "9", null,  "7", null, null,  "2", null,  "6", null },
                            { null,  "5",  "2",  "3", null, null,  "8", null, null,  "4" },
                            { null,  "4", null, null,  "1", null, null, null, null, null } },
            //easy
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null, null,  "3",  "4",  "6", null, null, null, null, null },
                            { null,  "8",  "9", null,  "1", null,  "4", null,  "7", null },
                            { null,  "6", null, null, null,  "7", null, null, null,  "4" },
                            { null,  "1",  "7", null, null,  "9", null, null,  "6",  "3" },
                            { null, null, null,  "9", null, null, null,  "1", null, null },
                            { null,  "3",  "2", null, null,  "8", null, null,  "5",  "7" },
                            { null,  "4", null, null, null,  "2", null, null, null,  "9" },
                            { null, null,  "8", null,  "9", null,  "3", null,  "4",  "5" },
                            { null, null, null, null, null, null,  "8",  "3",  "1", null } },
            //med
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null,  "8",  "4", null,  "1",  "2", null,  "6",  "9", null },
                            { null, null, null, null,  "3", null, null,  "4", null,  "2" },
                            { null, null,  "2",  "3", null, null, null, null,  "5", null },
                            { null, null,  "5", null, null, null,  "2", null,  "6", null },
                            { null,  "6", null, null,  "4",  "9",  "7", null, null,  "5" },
                            { null, null,  "1", null,  "5", null, null, null,  "2", null },
                            { null, null,  "7", null, null, null, null,  "9",  "8", null },
                            { null,  "2", null, null, null, null,  "3", null, null, null },
                            { null, null,  "9",  "6", null,  "4",  "8", null,  "3",  "1" } },
            //med
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null,  "4",  "1", null, null, null, null,  "5", null,  "7" },
                            { null, null, null,  "3", null, null,  "9", null,  "8", null },
                            { null,  "8", null, null,  "5", null, null,  "2", null, null },
                            { null,  "9", null, null,  "3", null,  "1", null, null, null },
                            { null, null, null, null,  "7",  "4",  "5", null, null, null },
                            { null, null, null, null,  "9", null,  "2", null, null,  "8" },
                            { null, null, null,  "9", null, null,  "4", null, null,  "3" },
                            { null, null,  "2", null,  "8", null, null,  "1", null, null },
                            { null,  "6", null,  "7", null, null, null, null,  "4",  "2" } },
            //med
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null, null,  "4",  "3", null, null, null,  "2", null, null },
                            { null, null,  "6", null, null, null, null, null,  "9", null },
                            { null, null,  "2", null,  "3",  "7",  "6", null, null, null },
                            { null,  "1",  "5", null, null,  "3", null, null, null, null },
                            { null,  "6", null,  "2", null, null, null,  "8", null,  "1" },
                            { null, null, null, null, null,  "5", null, null,  "6",  "7" },
                            { null, null, null, null,  "4",  "8",  "1", null,  "7", null },
                            { null, null,  "7", null, null, null, null, null,  "1", null },
                            { null, null, null,  "4", null, null, null,  "5",  "3", null } },
            //med
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null,  "4",  "9", null,  "7", null, null,  "6", null, null },
                            { null, null,  "2", null,  "6", null, null, null,  "7",  "3" },
                            { null, null, null, null, null,  "2",  "3",  "5", null, null },
                            { null, null, null,  "6", null, null, null,  "1", null, null },
                            { null,  "1",  "8", null,  "5", null,  "6", null,  "4",  "9" },
                            { null, null, null,  "4", null, null, null,  "8", null, null },
                            { null, null, null,  "5",  "3",  "4", null, null, null, null },
                            { null,  "7",  "4", null, null, null,  "9", null,  "5", null },
                            { null, null, null,  "9", null, null,  "7", null,  "6",  "1" } },
            //hard
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null, null,  "7", null, null, null,  "5",  "4", null, null },
                            { null, null, null,  "8", null,  "4", null, null, null,  "1" },
                            { null, null,  "1", null, null, null, null, null,  "5", null },
                            { null, null,  "3",  "4",  "9",  "8", null, null, null, null },
                            { null, null, null,  "7", null, null, null,  "9", null, null },
                            { null, null, null, null, null,  "1",  "4",  "5",  "3", null },
                            { null, null,  "4", null, null, null, null, null,  "2", null },
                            { null,  "6", null, null, null,  "3", null,  "7", null, null },
                            { null, null, null,  "2",  "6", null, null, null,  "1", null } },
            //hard
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null, null, null, null,  "3", null, null,  "6", null,  "8" },
                            { null, null,  "3",  "5", null, null,  "1", null, null, null },
                            { null, null, null, null, null,  "7",  "5",  "2", null, null },
                            { null,  "4", null,  "8", null, null, null,  "9", null, null },
                            { null, null,  "1", null, null, null, null, null,  "3", null },
                            { null, null, null,  "9", null, null, null,  "1", null,  "2" },
                            { null, null, null,  "7",  "5",  "4", null, null, null, null },
                            { null, null, null, null,  "6", null, null,  "8",  "4", null },
                            { null,  "2", null,  "4", null, null,  "9", null, null, null } },
            //hard
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null, null, null, null,  "8", null,  "6", null, null,  "7" },
                            { null, null, null, null, null,  "3", null, null, null,  "2" },
                            { null, null, null, null, null, null,  "2", null,  "8",  "1" },
                            { null, null,  "3", null,  "2",  "1", null,  "4",  "6", null },
                            { null, null, null,  "1", null, null, null,  "7", null, null },
                            { null, null,  "2",  "7", null,  "9",  "8", null,  "1", null },
                            { null,  "5",  "7", null,  "6", null, null, null, null, null },
                            { null,  "1", null, null, null,  "8", null, null, null, null },
                            { null,  "9", null, null,  "3", null,  "5", null, null, null } },
            //evil
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null, null, null, null, null, null, null,  "2",  "9", null },
                            { null, null, null, null,  "2", null,  "9", null, null,  "7" },
                            { null,  "2", null, null, null, null,  "5", null,  "8", null },
                            { null, null, null,  "6", null, null,  "1",  "7", null, null },
                            { null,  "9", null,  "8", null, null, null,  "3", null, null },
                            { null, null, null,  "1",  "8", null, null,  "5", null, null },
                            { null, null,  "7", null,  "3", null, null, null, null,  "1" },
                            { null,  "8", null, null,  "5", null,  "7", null, null, null },
                            { null, null,  "4",  "2", null, null, null, null, null, null } },
            //evil
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null, null,  "6",  "8", null, null, null, null, null,  "4" },
                            { null,  "1", null, null, null,  "5", null, null, null, null },
                            { null,  "7", null,  "5", null, null, null, null,  "2",  "1" },
                            { null, null, null, null, null, null,  "3",  "4", null, null },
                            { null, null,  "7", null,  "4", null,  "8", null,  "9", null },
                            { null, null, null,  "4",  "6", null, null, null, null, null },
                            { null,  "2",  "3", null, null, null, null,  "9", null,  "6" },
                            { null, null, null, null, null,  "9", null, null, null,  "5" },
                            { null,  "4", null, null, null, null, null,  "8",  "3", null } },
            //evil
            new string[,] { { null, null, null, null, null, null, null, null, null, null },
                            { null, null, null,  "2", null,  "1", null,  "7", null,  "9" },
                            { null, null, null, null, null,  "5",  "9", null, null,  "2" },
                            { null, null, null, null,  "8", null, null, null,  "1", null },
                            { null, null,  "4",  "6", null, null,  "3", null, null, null },
                            { null,  "7", null, null, null, null, null, null, null,  "1" },
                            { null, null, null, null,  "5", null, null,  "8",  "9", null },
                            { null, null,  "6", null, null, null,  "8", null, null, null },
                            { null,  "5", null, null,  "4",  "2", null, null, null, null },
                            { null,  "9", null,  "4", null,  "3", null,  "2", null, null } }
        };   
    }
}
